define(
//begin v1.x content
{
	"dateFormatItem-yM": "Gy/M",
	"dateFormatItem-yQ": "Gyå¹´QQQ",
	"dayPeriods-format-wide-pm": "ä¸‹å?ˆ",
	"dateFormatItem-MMMEd": "MMMdæ—¥E",
	"dateTimeFormat-full": "{1}{0}",
	"dateFormatItem-hms": "ah:mm:ss",
	"dateFormatItem-yQQQ": "Gyå¹´QQQ",
	"dateFormatItem-MMdd": "MM/dd",
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "ä¸Šå?ˆ",
	"dateFormatItem-y": "Gyå¹´",
	"timeFormat-full": "zzzzahæ™‚mmåˆ†ssç§’",
	"dateFormatItem-yyyy": "yå¹´",
	"months-standAlone-abbr": [
		"ä¸€æœˆ",
		"äºŒæœˆ",
		"ä¸‰æœˆ",
		"å››æœˆ",
		"äº”æœˆ",
		"å…­æœˆ",
		"ä¸ƒæœˆ",
		"å…«æœˆ",
		"ä¹?æœˆ",
		"å??æœˆ",
		"å??ä¸€æœˆ",
		"å??äºŒæœˆ"
	],
	"dateFormatItem-Ed": "dæ—¥(E)",
	"dateFormatItem-yMMM": "Gyå¹´Mæœˆ",
	"days-standAlone-narrow": [
		"æ—¥",
		"ä¸€",
		"äºŒ",
		"ä¸‰",
		"å››",
		"äº”",
		"å…­"
	],
	"dateFormatItem-yyyyMMMM": "yå¹´MMMM",
	"dateFormat-long": "Gyå¹´Mæœˆdæ—¥",
	"timeFormat-medium": "ah:mm:ss",
	"dateFormatItem-EEEd": "d EEE",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-yyMM": "Gyy/MM",
	"dateFormat-medium": "Gy/M/d",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yyMMM": "Gyyå¹´MMM",
	"dateFormatItem-yMd": "Gy/M/d",
	"dateFormatItem-ms": "mm:ss",
	"dateTimeFormat-long": "{1}{0}",
	"months-standAlone-wide": [
		"ä¸€æœˆ",
		"äºŒæœˆ",
		"ä¸‰æœˆ",
		"å››æœˆ",
		"äº”æœˆ",
		"å…­æœˆ",
		"ä¸ƒæœˆ",
		"å…«æœˆ",
		"ä¹?æœˆ",
		"å??æœˆ",
		"å??ä¸€æœˆ",
		"å??äºŒæœˆ"
	],
	"dateFormatItem-MMMd": "MMMdæ—¥",
	"dateFormatItem-yyQ": "Gyyå¹´ç¬¬Qå­£åº¦",
	"timeFormat-long": "zahæ™‚mmåˆ†ssç§’",
	"months-format-abbr": [
		"1æœˆ",
		"2æœˆ",
		"3æœˆ",
		"4æœˆ",
		"5æœˆ",
		"6æœˆ",
		"7æœˆ",
		"8æœˆ",
		"9æœˆ",
		"10æœˆ",
		"11æœˆ",
		"12æœˆ"
	],
	"dateFormatItem-H": "Hæ™‚",
	"timeFormat-short": "ah:mm",
	"quarters-format-abbr": [
		"1å­£",
		"2å­£",
		"3å­£",
		"4å­£"
	],
	"dateFormatItem-MMMMdd": "MMMMddæ—¥",
	"days-format-abbr": [
		"é€±æ—¥",
		"é€±ä¸€",
		"é€±äºŒ",
		"é€±ä¸‰",
		"é€±å››",
		"é€±äº”",
		"é€±å…­"
	],
	"dateFormatItem-M": "Mæœˆ",
	"dateFormatItem-yMMMd": "Gyå¹´MMMdæ—¥",
	"dateFormatItem-MEd": "M/dï¼ˆEï¼‰",
	"dateFormatItem-hm": "ah:mm",
	"dateFormat-short": "Gy/M/d",
	"dateFormatItem-yyyyM": "yå¹´Mæœˆ",
	"dateFormatItem-yMMMEd": "Gyå¹´Mæœˆdæ—¥EEE",
	"dateFormat-full": "Gyå¹´Mæœˆdæ—¥EEEE",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "Gy/M/dï¼ˆEEEï¼‰",
	"months-format-wide": [
		"1æœˆ",
		"2æœˆ",
		"3æœˆ",
		"4æœˆ",
		"5æœˆ",
		"6æœˆ",
		"7æœˆ",
		"8æœˆ",
		"9æœˆ",
		"10æœˆ",
		"11æœˆ",
		"12æœˆ"
	],
	"dateFormatItem-d": "dæ—¥",
	"quarters-format-wide": [
		"ç¬¬1å­£",
		"ç¬¬2å­£",
		"ç¬¬3å­£",
		"ç¬¬4å­£"
	],
	"days-format-wide": [
		"æ˜ŸæœŸæ—¥",
		"æ˜ŸæœŸä¸€",
		"æ˜ŸæœŸäºŒ",
		"æ˜ŸæœŸä¸‰",
		"æ˜ŸæœŸå››",
		"æ˜ŸæœŸäº”",
		"æ˜ŸæœŸå…­"
	],
	"dateFormatItem-h": "ahæ™‚"
}
//end v1.x content
);