define(
//begin v1.x content
{
	"field-weekday": "é€±å¤©",
	"dateFormatItem-yQQQ": "yå¹´QQQ",
	"dateFormatItem-yMEd": "yyyy/M/dï¼ˆEEEï¼‰",
	"dateFormatItem-MMMEd": "MMMdæ—¥E",
	"eraNarrow": [
		"è¥¿å…ƒå‰?",
		"è¥¿å…ƒ"
	],
	"dateFormat-long": "yå¹´Mæœˆdæ—¥",
	"months-format-wide": [
		"1æœˆ",
		"2æœˆ",
		"3æœˆ",
		"4æœˆ",
		"5æœˆ",
		"6æœˆ",
		"7æœˆ",
		"8æœˆ",
		"9æœˆ",
		"10æœˆ",
		"11æœˆ",
		"12æœˆ"
	],
	"dateTimeFormat-medium": "{1} {0}",
	"dayPeriods-format-wide-pm": "ä¸‹å?ˆ",
	"dateFormat-full": "yå¹´Mæœˆdæ—¥EEEE",
	"dateFormatItem-Md": "M/d",
	"field-era": "å¹´ä»£",
	"dateFormatItem-yM": "yyyy/M",
	"months-standAlone-wide": [
		"1æœˆ",
		"2æœˆ",
		"3æœˆ",
		"4æœˆ",
		"5æœˆ",
		"6æœˆ",
		"7æœˆ",
		"8æœˆ",
		"9æœˆ",
		"10æœˆ",
		"11æœˆ",
		"12æœˆ"
	],
	"timeFormat-short": "ah:mm",
	"quarters-format-wide": [
		"ç¬¬1å­£",
		"ç¬¬2å­£",
		"ç¬¬3å­£",
		"ç¬¬4å­£"
	],
	"timeFormat-long": "zahæ™‚mmåˆ†ssç§’",
	"field-year": "å¹´",
	"dateFormatItem-yMMM": "yå¹´Mæœˆ",
	"dateFormatItem-yQ": "yå¹´QQQ",
	"field-hour": "å°?æ™‚",
	"dateFormatItem-MMdd": "MM/dd",
	"months-format-abbr": [
		"1æœˆ",
		"2æœˆ",
		"3æœˆ",
		"4æœˆ",
		"5æœˆ",
		"6æœˆ",
		"7æœˆ",
		"8æœˆ",
		"9æœˆ",
		"10æœˆ",
		"11æœˆ",
		"12æœˆ"
	],
	"dateFormatItem-yyQ": "yyå¹´ç¬¬Qå­£åº¦",
	"timeFormat-full": "zzzzahæ™‚mmåˆ†ssç§’",
	"field-day-relative+0": "ä»Šå¤©",
	"field-day-relative+1": "æ˜Žå¤©",
	"field-day-relative+2": "å¾Œå¤©",
	"dateFormatItem-H": "Hæ™‚",
	"field-day-relative+3": "å¤§å¾Œå¤©",
	"months-standAlone-abbr": [
		"ä¸€æœˆ",
		"äºŒæœˆ",
		"ä¸‰æœˆ",
		"å››æœˆ",
		"äº”æœˆ",
		"å…­æœˆ",
		"ä¸ƒæœˆ",
		"å…«æœˆ",
		"ä¹?æœˆ",
		"å??æœˆ",
		"å??ä¸€æœˆ",
		"å??äºŒæœˆ"
	],
	"quarters-format-abbr": [
		"1å­£",
		"2å­£",
		"3å­£",
		"4å­£"
	],
	"quarters-standAlone-wide": [
		"ç¬¬1å­£",
		"ç¬¬2å­£",
		"ç¬¬3å­£",
		"ç¬¬4å­£"
	],
	"dateFormatItem-M": "Mæœˆ",
	"days-standAlone-wide": [
		"æ˜ŸæœŸæ—¥",
		"æ˜ŸæœŸä¸€",
		"æ˜ŸæœŸäºŒ",
		"æ˜ŸæœŸä¸‰",
		"æ˜ŸæœŸå››",
		"æ˜ŸæœŸäº”",
		"æ˜ŸæœŸå…­"
	],
	"dateFormatItem-yyMMM": "yyå¹´MMM",
	"timeFormat-medium": "ah:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"quarters-standAlone-abbr": [
		"1å­£",
		"2å­£",
		"3å­£",
		"4å­£"
	],
	"eraAbbr": [
		"è¥¿å…ƒå‰?",
		"è¥¿å…ƒ"
	],
	"field-minute": "åˆ†é?˜",
	"field-dayperiod": "ä¸Šå?ˆ/ä¸‹å?ˆ",
	"days-standAlone-abbr": [
		"é€±æ—¥",
		"é€±ä¸€",
		"é€±äºŒ",
		"é€±ä¸‰",
		"é€±å››",
		"é€±äº”",
		"é€±å…­"
	],
	"dateFormatItem-d": "dæ—¥",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "æ˜¨å¤©",
	"dateFormatItem-h": "ahæ™‚",
	"dateTimeFormat-long": "{1}{0}",
	"field-day-relative+-2": "å‰?å¤©",
	"field-day-relative+-3": "å¤§å‰?å¤©",
	"dateFormatItem-MMMd": "MMMdæ—¥",
	"dateFormatItem-MEd": "M/dï¼ˆEï¼‰",
	"dateTimeFormat-full": "{1}{0}",
	"field-day": "æ—¥",
	"days-format-wide": [
		"æ˜ŸæœŸæ—¥",
		"æ˜ŸæœŸä¸€",
		"æ˜ŸæœŸäºŒ",
		"æ˜ŸæœŸä¸‰",
		"æ˜ŸæœŸå››",
		"æ˜ŸæœŸäº”",
		"æ˜ŸæœŸå…­"
	],
	"field-zone": "å?€åŸŸ",
	"dateFormatItem-y": "yå¹´",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateFormatItem-yyMM": "yy-MM",
	"dateFormatItem-hm": "ah:mm",
	"days-format-abbr": [
		"é€±æ—¥",
		"é€±ä¸€",
		"é€±äºŒ",
		"é€±ä¸‰",
		"é€±å››",
		"é€±äº”",
		"é€±å…­"
	],
	"dateFormatItem-yMMMd": "yå¹´MMMdæ—¥",
	"eraNames": [
		"è¥¿å…ƒå‰?",
		"è¥¿å…ƒ"
	],
	"days-format-narrow": [
		"æ—¥",
		"ä¸€",
		"äºŒ",
		"ä¸‰",
		"å››",
		"äº”",
		"å…­"
	],
	"field-month": "æœˆ",
	"days-standAlone-narrow": [
		"æ—¥",
		"ä¸€",
		"äºŒ",
		"ä¸‰",
		"å››",
		"äº”",
		"å…­"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "ä¸Šå?ˆ",
	"dateFormatItem-MMMMdd": "MMMMddæ—¥",
	"dateFormat-short": "yy/M/d",
	"field-second": "ç§’",
	"dateFormatItem-yMMMEd": "yå¹´Mæœˆdæ—¥EEE",
	"dateFormatItem-Ed": "dæ—¥(E)",
	"field-week": "é€±",
	"dateFormat-medium": "yyyy/M/d",
	"dateFormatItem-yyyyM": "yå¹´Mæœˆ",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hms": "ah:mm:ss",
	"dateFormatItem-yyyy": "yå¹´"
}
//end v1.x content
);