define(
//begin v1.x content
{
	"months-format-narrow": [
		"1æœˆ",
		"2æœˆ",
		"3æœˆ",
		"4æœˆ",
		"5æœˆ",
		"6æœˆ",
		"7æœˆ",
		"8æœˆ",
		"9æœˆ",
		"10æœˆ",
		"11æœˆ",
		"12æœˆ"
	],
	"field-weekday": "å‘¨å¤©",
	"dateFormatItem-yQQQ": "yå¹´QQQ",
	"dateFormatItem-yMEd": "yå¹´Mæœˆdæ—¥ï¼ŒE",
	"dateFormatItem-MMMEd": "MMMdæ—¥E",
	"eraNarrow": [
		"å…¬å…ƒå‰?",
		"å…¬å…ƒ"
	],
	"dayPeriods-format-wide-earlyMorning": "æ¸…æ™¨",
	"dayPeriods-format-wide-morning": "ä¸Šå?ˆ",
	"dateFormat-long": "yå¹´Mæœˆdæ—¥",
	"months-format-wide": [
		"1æœˆ",
		"2æœˆ",
		"3æœˆ",
		"4æœˆ",
		"5æœˆ",
		"6æœˆ",
		"7æœˆ",
		"8æœˆ",
		"9æœˆ",
		"10æœˆ",
		"11æœˆ",
		"12æœˆ"
	],
	"dateTimeFormat-medium": "{1} {0}",
	"dayPeriods-format-wide-pm": "ä¸‹å?ˆ",
	"dateFormat-full": "yå¹´Mæœˆdæ—¥EEEE",
	"dateFormatItem-Md": "M-d",
	"field-era": "æ—¶æœŸ",
	"dateFormatItem-yM": "yyyy-M",
	"months-standAlone-wide": [
		"ä¸€æœˆ",
		"äºŒæœˆ",
		"ä¸‰æœˆ",
		"å››æœˆ",
		"äº”æœˆ",
		"å…­æœˆ",
		"ä¸ƒæœˆ",
		"å…«æœˆ",
		"ä¹?æœˆ",
		"å??æœˆ",
		"å??ä¸€æœˆ",
		"å??äºŒæœˆ"
	],
	"timeFormat-short": "ah:mm",
	"quarters-format-wide": [
		"ç¬¬1å­£åº¦",
		"ç¬¬2å­£åº¦",
		"ç¬¬3å­£åº¦",
		"ç¬¬4å­£åº¦"
	],
	"timeFormat-long": "zahæ—¶mmåˆ†ssç§’",
	"field-year": "å¹´",
	"dateFormatItem-yMMM": "yå¹´MMM",
	"dateFormatItem-yQ": "yå¹´QQQ",
	"dateFormatItem-yyyyMMMM": "yå¹´MMMM",
	"field-hour": "å°?æ—¶",
	"dateFormatItem-MMdd": "MM-dd",
	"months-format-abbr": [
		"1æœˆ",
		"2æœˆ",
		"3æœˆ",
		"4æœˆ",
		"5æœˆ",
		"6æœˆ",
		"7æœˆ",
		"8æœˆ",
		"9æœˆ",
		"10æœˆ",
		"11æœˆ",
		"12æœˆ"
	],
	"dateFormatItem-yyQ": "yyå¹´ç¬¬Qå­£åº¦",
	"timeFormat-full": "zzzzahæ—¶mmåˆ†ssç§’",
	"field-day-relative+0": "ä»Šå¤©",
	"field-day-relative+1": "æ˜Žå¤©",
	"field-day-relative+2": "å?Žå¤©",
	"dateFormatItem-H": "Hæ—¶",
	"months-standAlone-abbr": [
		"ä¸€æœˆ",
		"äºŒæœˆ",
		"ä¸‰æœˆ",
		"å››æœˆ",
		"äº”æœˆ",
		"å…­æœˆ",
		"ä¸ƒæœˆ",
		"å…«æœˆ",
		"ä¹?æœˆ",
		"å??æœˆ",
		"å??ä¸€æœˆ",
		"å??äºŒæœˆ"
	],
	"quarters-format-abbr": [
		"1å­£",
		"2å­£",
		"3å­£",
		"4å­£"
	],
	"quarters-standAlone-wide": [
		"ç¬¬1å­£åº¦",
		"ç¬¬2å­£åº¦",
		"ç¬¬3å­£åº¦",
		"ç¬¬4å­£åº¦"
	],
	"dateFormatItem-M": "Mæœˆ",
	"days-standAlone-wide": [
		"æ˜ŸæœŸæ—¥",
		"æ˜ŸæœŸä¸€",
		"æ˜ŸæœŸäºŒ",
		"æ˜ŸæœŸä¸‰",
		"æ˜ŸæœŸå››",
		"æ˜ŸæœŸäº”",
		"æ˜ŸæœŸå…­"
	],
	"dateFormatItem-yyMMM": "yyå¹´MMM",
	"timeFormat-medium": "ah:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"quarters-standAlone-abbr": [
		"1å­£",
		"2å­£",
		"3å­£",
		"4å­£"
	],
	"eraAbbr": [
		"å…¬å…ƒå‰?",
		"å…¬å…ƒ"
	],
	"field-minute": "åˆ†é’Ÿ",
	"field-dayperiod": "ä¸Šå?ˆ/ä¸‹å?ˆ",
	"days-standAlone-abbr": [
		"å‘¨æ—¥",
		"å‘¨ä¸€",
		"å‘¨äºŒ",
		"å‘¨ä¸‰",
		"å‘¨å››",
		"å‘¨äº”",
		"å‘¨å…­"
	],
	"dayPeriods-format-wide-night": "æ™šä¸Š",
	"dateFormatItem-d": "dæ—¥",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "æ˜¨å¤©",
	"dateFormatItem-h": "ahæ—¶",
	"dateTimeFormat-long": "{1}{0}",
	"field-day-relative+-2": "å‰?å¤©",
	"dateFormatItem-MMMd": "MMMdæ—¥",
	"dayPeriods-format-wide-midDay": "ä¸­å?ˆ",
	"dateFormatItem-MEd": "M-dE",
	"dateTimeFormat-full": "{1}{0}",
	"field-day": "æ—¥",
	"days-format-wide": [
		"æ˜ŸæœŸæ—¥",
		"æ˜ŸæœŸä¸€",
		"æ˜ŸæœŸäºŒ",
		"æ˜ŸæœŸä¸‰",
		"æ˜ŸæœŸå››",
		"æ˜ŸæœŸäº”",
		"æ˜ŸæœŸå…­"
	],
	"field-zone": "åŒºåŸŸ",
	"dateFormatItem-y": "yå¹´",
	"months-standAlone-narrow": [
		"1æœˆ",
		"2æœˆ",
		"3æœˆ",
		"4æœˆ",
		"5æœˆ",
		"6æœˆ",
		"7æœˆ",
		"8æœˆ",
		"9æœˆ",
		"10æœˆ",
		"11æœˆ",
		"12æœˆ"
	],
	"dateFormatItem-yyMM": "yy-MM",
	"dateFormatItem-hm": "ah:mm",
	"days-format-abbr": [
		"å‘¨æ—¥",
		"å‘¨ä¸€",
		"å‘¨äºŒ",
		"å‘¨ä¸‰",
		"å‘¨å››",
		"å‘¨äº”",
		"å‘¨å…­"
	],
	"dateFormatItem-yMMMd": "yå¹´MMMdæ—¥",
	"eraNames": [
		"å…¬å…ƒå‰?",
		"å…¬å…ƒ"
	],
	"days-format-narrow": [
		"æ—¥",
		"ä¸€",
		"äºŒ",
		"ä¸‰",
		"å››",
		"äº”",
		"å…­"
	],
	"field-month": "æœˆ",
	"days-standAlone-narrow": [
		"æ—¥",
		"ä¸€",
		"äºŒ",
		"ä¸‰",
		"å››",
		"äº”",
		"å…­"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "ä¸Šå?ˆ",
	"dateFormatItem-MMMMdd": "MMMMddæ—¥",
	"dayPeriods-format-wide-weeHours": "å‡Œæ™¨",
	"dateFormat-short": "yy-M-d",
	"dayPeriods-format-wide-afternoon": "ä¸‹å?ˆ",
	"field-second": "ç§’é’Ÿ",
	"dateFormatItem-yMMMEd": "yå¹´MMMdæ—¥EEE",
	"dateFormatItem-Ed": "dæ—¥E",
	"field-week": "å‘¨",
	"dateFormat-medium": "yyyy-M-d",
	"dateFormatItem-yyyyM": "yå¹´Mæœˆ",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hms": "ah:mm:ss",
	"dateFormatItem-yyyy": "yå¹´"
}
//end v1.x content
);