define(
//begin v1.x content
{
	"months-format-narrow": [
		"1ì›”",
		"2ì›”",
		"3ì›”",
		"4ì›”",
		"5ì›”",
		"6ì›”",
		"7ì›”",
		"8ì›”",
		"9ì›”",
		"10ì›”",
		"11ì›”",
		"12ì›”"
	],
	"field-weekday": "ìš”ì?¼",
	"dateFormatItem-yQQQ": "yë…„ QQQ",
	"dateFormatItem-yMEd": "yyyy. M. d. EEE",
	"dateFormatItem-MMMEd": "MMM dì?¼ (E)",
	"eraNarrow": [
		"ê¸°ì›?ì „",
		"ì„œê¸°"
	],
	"dateFormat-long": "yë…„ Mì›” dì?¼",
	"months-format-wide": [
		"1ì›”",
		"2ì›”",
		"3ì›”",
		"4ì›”",
		"5ì›”",
		"6ì›”",
		"7ì›”",
		"8ì›”",
		"9ì›”",
		"10ì›”",
		"11ì›”",
		"12ì›”"
	],
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormatItem-EEEd": "dì?¼ EEE",
	"dayPeriods-format-wide-pm": "ì˜¤í›„",
	"dateFormat-full": "yë…„ Mì›” dì?¼ EEEE",
	"dateFormatItem-Md": "M. d.",
	"field-era": "ì—°í˜¸",
	"dateFormatItem-yM": "yyyy. M.",
	"months-standAlone-wide": [
		"1ì›”",
		"2ì›”",
		"3ì›”",
		"4ì›”",
		"5ì›”",
		"6ì›”",
		"7ì›”",
		"8ì›”",
		"9ì›”",
		"10ì›”",
		"11ì›”",
		"12ì›”"
	],
	"timeFormat-short": "a h:mm",
	"quarters-format-wide": [
		"ì œ 1/4ë¶„ê¸°",
		"ì œ 2/4ë¶„ê¸°",
		"ì œ 3/4ë¶„ê¸°",
		"ì œ 4/4ë¶„ê¸°"
	],
	"timeFormat-long": "a hì‹œ më¶„ sì´ˆ z",
	"field-year": "ë…„",
	"dateFormatItem-yMMM": "yë…„ MMM",
	"dateFormatItem-yQ": "yë…„ Që¶„ê¸°",
	"field-hour": "ì‹œ",
	"dateFormatItem-MMdd": "MM. dd",
	"months-format-abbr": [
		"1ì›”",
		"2ì›”",
		"3ì›”",
		"4ì›”",
		"5ì›”",
		"6ì›”",
		"7ì›”",
		"8ì›”",
		"9ì›”",
		"10ì›”",
		"11ì›”",
		"12ì›”"
	],
	"dateFormatItem-yyQ": "yyë…„ Që¶„ê¸°",
	"timeFormat-full": "a hì‹œ më¶„ sì´ˆ zzzz",
	"field-day-relative+0": "ì˜¤ëŠ˜",
	"field-day-relative+1": "ë‚´ì?¼",
	"field-day-relative+2": "ëª¨ë ˆ",
	"dateFormatItem-H": "Hì‹œ",
	"field-day-relative+3": "3ì?¼í›„",
	"months-standAlone-abbr": [
		"1ì›”",
		"2ì›”",
		"3ì›”",
		"4ì›”",
		"5ì›”",
		"6ì›”",
		"7ì›”",
		"8ì›”",
		"9ì›”",
		"10ì›”",
		"11ì›”",
		"12ì›”"
	],
	"quarters-format-abbr": [
		"1ë¶„ê¸°",
		"2ë¶„ê¸°",
		"3ë¶„ê¸°",
		"4ë¶„ê¸°"
	],
	"quarters-standAlone-wide": [
		"ì œ 1/4ë¶„ê¸°",
		"ì œ 2/4ë¶„ê¸°",
		"ì œ 3/4ë¶„ê¸°",
		"ì œ 4/4ë¶„ê¸°"
	],
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"dateFormatItem-M": "Mì›”",
	"days-standAlone-wide": [
		"ì?¼ìš”ì?¼",
		"ì›”ìš”ì?¼",
		"í™”ìš”ì?¼",
		"ìˆ˜ìš”ì?¼",
		"ëª©ìš”ì?¼",
		"ê¸ˆìš”ì?¼",
		"í† ìš”ì?¼"
	],
	"dateFormatItem-yyMMM": "yyë…„ MMM",
	"timeFormat-medium": "a h:mm:ss",
	"dateFormatItem-Hm": "HH:mm",
	"quarters-standAlone-abbr": [
		"1ë¶„ê¸°",
		"2ë¶„ê¸°",
		"3ë¶„ê¸°",
		"4ë¶„ê¸°"
	],
	"eraAbbr": [
		"ê¸°ì›?ì „",
		"ì„œê¸°"
	],
	"field-minute": "ë¶„",
	"field-dayperiod": "ì˜¤ì „/ì˜¤í›„",
	"days-standAlone-abbr": [
		"ì?¼",
		"ì›”",
		"í™”",
		"ìˆ˜",
		"ëª©",
		"ê¸ˆ",
		"í† "
	],
	"dateFormatItem-d": "dì?¼",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "ì–´ì œ",
	"dateFormatItem-h": "a hì‹œ",
	"dateTimeFormat-long": "{1} {0}",
	"field-day-relative+-2": "ê·¸ì €ê»˜",
	"field-day-relative+-3": "ê·¸ë?„ì œ",
	"dateFormatItem-MMMd": "MMM dì?¼",
	"dateFormatItem-MEd": "M. d. (E)",
	"dateTimeFormat-full": "{1} {0}",
	"field-day": "ì?¼",
	"days-format-wide": [
		"ì?¼ìš”ì?¼",
		"ì›”ìš”ì?¼",
		"í™”ìš”ì?¼",
		"ìˆ˜ìš”ì?¼",
		"ëª©ìš”ì?¼",
		"ê¸ˆìš”ì?¼",
		"í† ìš”ì?¼"
	],
	"field-zone": "ì‹œê°„ëŒ€",
	"dateFormatItem-yyyyMM": "yyyy. MM",
	"dateFormatItem-y": "yë…„",
	"months-standAlone-narrow": [
		"1ì›”",
		"2ì›”",
		"3ì›”",
		"4ì›”",
		"5ì›”",
		"6ì›”",
		"7ì›”",
		"8ì›”",
		"9ì›”",
		"10ì›”",
		"11ì›”",
		"12ì›”"
	],
	"dateFormatItem-yyMM": "YY. M.",
	"dateFormatItem-hm": "a h:mm",
	"days-format-abbr": [
		"ì?¼",
		"ì›”",
		"í™”",
		"ìˆ˜",
		"ëª©",
		"ê¸ˆ",
		"í† "
	],
	"dateFormatItem-yMMMd": "yë…„ MMM dì?¼",
	"eraNames": [
		"ì„œë ¥ê¸°ì›?ì „",
		"ì„œë ¥ê¸°ì›?"
	],
	"days-format-narrow": [
		"ì?¼",
		"ì›”",
		"í™”",
		"ìˆ˜",
		"ëª©",
		"ê¸ˆ",
		"í† "
	],
	"field-month": "ì›”",
	"days-standAlone-narrow": [
		"ì?¼",
		"ì›”",
		"í™”",
		"ìˆ˜",
		"ëª©",
		"ê¸ˆ",
		"í† "
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "ì˜¤ì „",
	"dateFormat-short": "yy. M. d.",
	"field-second": "ì´ˆ",
	"dateFormatItem-yMMMEd": "yë…„ MMM dì?¼ EEE",
	"dateFormatItem-Ed": "dì?¼ (E)",
	"field-week": "ì£¼",
	"dateFormat-medium": "yyyy. M. d.",
	"dateFormatItem-mmss": "mm:ss",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "Hì‹œ më¶„ sì´ˆ",
	"dateFormatItem-hms": "a h:mm:ss"
}
//end v1.x content
);