define(
//begin v1.x content
{
	"months-format-narrow": [
		"T",
		"H",
		"M",
		"H",
		"T",
		"K",
		"H",
		"E",
		"S",
		"L",
		"M",
		"J"
	],
	"field-weekday": "viikonpÃ¤ivÃ¤",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "EEE d.M.yyyy",
	"dateFormatItem-MMMEd": "E d. MMM",
	"eraNarrow": [
		"eKr.",
		"jKr."
	],
	"dateFormat-long": "d. MMMM y",
	"months-format-wide": [
		"tammikuuta",
		"helmikuuta",
		"maaliskuuta",
		"huhtikuuta",
		"toukokuuta",
		"kesÃ¤kuuta",
		"heinÃ¤kuuta",
		"elokuuta",
		"syyskuuta",
		"lokakuuta",
		"marraskuuta",
		"joulukuuta"
	],
	"dayPeriods-format-wide-pm": "ip.",
	"dateFormat-full": "cccc d. MMMM y",
	"dateFormatItem-Md": "d.M.",
	"dayPeriods-standAlone-wide-pm": "ip.",
	"dayPeriods-format-abbr-am": "ap.",
	"field-era": "aikakausi",
	"dateFormatItem-yM": "L.yyyy",
	"months-standAlone-wide": [
		"tammikuu",
		"helmikuu",
		"maaliskuu",
		"huhtikuu",
		"toukokuu",
		"kesÃ¤kuu",
		"heinÃ¤kuu",
		"elokuu",
		"syyskuu",
		"lokakuu",
		"marraskuu",
		"joulukuu"
	],
	"timeFormat-short": "H.mm",
	"quarters-format-wide": [
		"1. neljÃ¤nnes",
		"2. neljÃ¤nnes",
		"3. neljÃ¤nnes",
		"4. neljÃ¤nnes"
	],
	"timeFormat-long": "H.mm.ss z",
	"field-year": "vuosi",
	"dateFormatItem-yMMM": "LLL y",
	"dateFormatItem-yQ": "Q/yyyy",
	"dateFormatItem-yyyyMMMM": "LLLL y",
	"field-hour": "tunti",
	"months-format-abbr": [
		"tammikuuta",
		"helmikuuta",
		"maaliskuuta",
		"huhtikuuta",
		"toukokuuta",
		"kesÃ¤kuuta",
		"heinÃ¤kuuta",
		"elokuuta",
		"syyskuuta",
		"lokakuuta",
		"marraskuuta",
		"joulukuuta"
	],
	"dateFormatItem-yyQ": "Q/yy",
	"timeFormat-full": "H.mm.ss zzzz",
	"dateFormatItem-yyyyMEEEd": "EEE d.M.yyyy",
	"field-day-relative+0": "tÃ¤nÃ¤Ã¤n",
	"field-day-relative+1": "huomenna",
	"field-day-relative+2": "ylihuomenna",
	"dateFormatItem-H": "H",
	"months-standAlone-abbr": [
		"tammi",
		"helmi",
		"maalis",
		"huhti",
		"touko",
		"kesÃ¤",
		"heinÃ¤",
		"elo",
		"syys",
		"loka",
		"marras",
		"joulu"
	],
	"quarters-format-abbr": [
		"1. nelj.",
		"2. nelj.",
		"3. nelj.",
		"4. nelj."
	],
	"quarters-standAlone-wide": [
		"1. neljÃ¤nnes",
		"2. neljÃ¤nnes",
		"3. neljÃ¤nnes",
		"4. neljÃ¤nnes"
	],
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"sunnuntai",
		"maanantai",
		"tiistai",
		"keskiviikko",
		"torstai",
		"perjantai",
		"lauantai"
	],
	"dateFormatItem-yyMMM": "LLLL yy",
	"timeFormat-medium": "H.mm.ss",
	"dateFormatItem-Hm": "H.mm",
	"quarters-standAlone-abbr": [
		"1. nelj.",
		"2. nelj.",
		"3. nelj.",
		"4. nelj."
	],
	"eraAbbr": [
		"eKr.",
		"jKr."
	],
	"field-minute": "minuutti",
	"field-dayperiod": "ap./ip.",
	"days-standAlone-abbr": [
		"su",
		"ma",
		"ti",
		"ke",
		"to",
		"pe",
		"la"
	],
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm.ss",
	"field-day-relative+-1": "eilen",
	"field-day-relative+-2": "toissapÃ¤ivÃ¤nÃ¤",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MEd": "E d.M.",
	"field-day": "pÃ¤ivÃ¤",
	"dateFormatItem-yMMMMccccd": "cccc, d. MMMM y",
	"days-format-wide": [
		"sunnuntaina",
		"maanantaina",
		"tiistaina",
		"keskiviikkona",
		"torstaina",
		"perjantaina",
		"lauantaina"
	],
	"field-zone": "aikavyÃ¶hyke",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"T",
		"H",
		"M",
		"H",
		"T",
		"K",
		"H",
		"E",
		"S",
		"L",
		"M",
		"J"
	],
	"dateFormatItem-yyMM": "M/yy",
	"dateFormatItem-hm": "h.mm a",
	"dayPeriods-format-abbr-pm": "ip.",
	"days-format-abbr": [
		"su",
		"ma",
		"ti",
		"ke",
		"to",
		"pe",
		"la"
	],
	"eraNames": [
		"ennen Kristuksen syntymÃ¤Ã¤",
		"jÃ¤lkeen Kristuksen syntymÃ¤n"
	],
	"days-format-narrow": [
		"S",
		"M",
		"T",
		"K",
		"T",
		"P",
		"L"
	],
	"field-month": "kuukausi",
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"K",
		"T",
		"P",
		"L"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "ap.",
	"dayPeriods-standAlone-wide-am": "ap.",
	"dateFormat-short": "d.M.yyyy",
	"field-second": "sekunti",
	"dateFormatItem-yMMMEd": "EEE d. MMM y",
	"dateFormatItem-Ed": "ccc d.",
	"field-week": "viikko",
	"dateFormat-medium": "d.M.yyyy",
	"dateFormatItem-yyyyM": "M/yyyy",
	"dateFormatItem-yyyyQQQQ": "QQQQ y",
	"dateFormatItem-Hms": "H.mm.ss",
	"dateFormatItem-hms": "h.mm.ss a"
}
//end v1.x content
);