define(
//begin v1.x content
{
	"dateFormatItem-yM": "L.yyyy",
	"dateFormatItem-yQ": "Q/yyyy",
	"months-standAlone-abbr-leap": "adÃ¡r II",
	"dayPeriods-format-wide-pm": "ip.",
	"dateFormatItem-MMMEd": "E d. MMM",
	"dateFormatItem-hms": "h.mm.ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"days-standAlone-wide": [
		"sunnuntai",
		"maanantai",
		"tiistai",
		"keskiviikko",
		"torstai",
		"perjantai",
		"lauantai"
	],
	"months-standAlone-narrow": [
		"T",
		"H",
		"K",
		"T",
		"S",
		"A",
		"A",
		"N",
		"I",
		"S",
		"T",
		"A",
		"E"
	],
	"dayPeriods-format-wide-am": "ap.",
	"timeFormat-full": "H.mm.ss zzzz",
	"months-standAlone-narrow-leap": "A",
	"months-standAlone-abbr": [
		"tiÅ¡rÃ­",
		"heÅ¡vÃ¡n",
		"kislÃ©v",
		"tevÃ©t",
		"Å¡evÃ¡t",
		"adÃ¡r I",
		"adÃ¡r",
		"nisÃ¡n",
		"ijjÃ¡r",
		"sivÃ¡n",
		"tammÃºz",
		"ab",
		"elÃºl"
	],
	"dateFormatItem-yMMM": "LLL y",
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"K",
		"T",
		"P",
		"L"
	],
	"dateFormat-long": "d. MMMM y",
	"timeFormat-medium": "H.mm.ss",
	"dateFormatItem-Hm": "H.mm",
	"dateFormat-medium": "d.M.yyyy",
	"dateFormatItem-Hms": "H.mm.ss",
	"dateFormatItem-ms": "mm.ss",
	"months-standAlone-wide": [
		"tiÅ¡rÃ­kuu",
		"heÅ¡vÃ¡nkuu",
		"kislÃ©vkuu",
		"tevÃ©tkuu",
		"Å¡evÃ¡tkuu",
		"adÃ¡rkuu I",
		"adÃ¡rkuu",
		"nisÃ¡nkuu",
		"ijjÃ¡rkuu",
		"sivÃ¡nkuu",
		"tammÃºzkuu",
		"abkuu",
		"elÃºlkuu"
	],
	"dateFormatItem-MMMd": "d. MMM",
	"timeFormat-long": "H.mm.ss z",
	"months-format-abbr": [
		"tiÅ¡rÃ­kuuta",
		"heÅ¡vÃ¡nkuuta",
		"kislÃ©vkuuta",
		"tevÃ©tkuuta",
		"Å¡evÃ¡tkuuta",
		"adÃ¡rkuuta I",
		"adÃ¡rkuuta",
		"nisÃ¡nkuuta",
		"ijjÃ¡rkuuta",
		"sivÃ¡nkuuta",
		"tammÃºzkuuta",
		"abkuuta",
		"elÃºlkuuta"
	],
	"timeFormat-short": "H.mm",
	"dateFormatItem-H": "H",
	"quarters-format-abbr": [
		"1. nelj.",
		"2. nelj.",
		"3. nelj.",
		"4. nelj."
	],
	"days-format-abbr": [
		"su",
		"ma",
		"ti",
		"ke",
		"to",
		"pe",
		"la"
	],
	"dateFormatItem-MEd": "E d.M.",
	"months-format-narrow": [
		"T",
		"H",
		"K",
		"T",
		"S",
		"A",
		"A",
		"N",
		"I",
		"S",
		"T",
		"A",
		"E"
	],
	"dateFormatItem-hm": "h.mm a",
	"months-standAlone-wide-leap": "adÃ¡rkuu II",
	"dayPeriods-format-abbr-pm": "ip.",
	"dateFormat-short": "d.M.yyyy",
	"dateFormatItem-yMMMEd": "EEE d. MMM y",
	"dateFormat-full": "cccc d. MMMM y",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yMEd": "EEE d.M.yyyy",
	"months-format-wide": [
		"tiÅ¡rÃ­kuuta",
		"heÅ¡vÃ¡nkuuta",
		"kislÃ©vkuuta",
		"tevÃ©tkuuta",
		"Å¡evÃ¡tkuuta",
		"adÃ¡rkuuta I",
		"adÃ¡rkuuta",
		"nisÃ¡nkuuta",
		"ijjÃ¡rkuuta",
		"sivÃ¡nkuuta",
		"tammÃºzkuuta",
		"abkuuta",
		"elÃºlkuuta"
	],
	"dayPeriods-format-abbr-am": "ap.",
	"quarters-format-wide": [
		"1. neljÃ¤nnes",
		"2. neljÃ¤nnes",
		"3. neljÃ¤nnes",
		"4. neljÃ¤nnes"
	],
	"months-format-wide-leap": "adÃ¡rkuuta II",
	"days-format-wide": [
		"sunnuntaina",
		"maanantaina",
		"tiistaina",
		"keskiviikkona",
		"torstaina",
		"perjantaina",
		"lauantaina"
	]
}
//end v1.x content
);