define(
//begin v1.x content
{
	"field-weekday": "æ›œæ—¥",
	"dateFormatItem-yQQQ": "yQQQ",
	"dateFormatItem-yMEd": "y/M/d(EEE)",
	"dateFormatItem-MMMEd": "Mæœˆdæ—¥(E)",
	"eraNarrow": [
		"BC",
		"AD"
	],
	"dateFormat-long": "yå¹´Mæœˆdæ—¥",
	"months-format-wide": [
		"1æœˆ",
		"2æœˆ",
		"3æœˆ",
		"4æœˆ",
		"5æœˆ",
		"6æœˆ",
		"7æœˆ",
		"8æœˆ",
		"9æœˆ",
		"10æœˆ",
		"11æœˆ",
		"12æœˆ"
	],
	"dateTimeFormat-medium": "{1} {0}",
	"dayPeriods-format-wide-pm": "å?ˆå¾Œ",
	"dateFormat-full": "yå¹´Mæœˆdæ—¥EEEE",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMd": "y/M/d",
	"field-era": "æ™‚ä»£",
	"dateFormatItem-yM": "y/M",
	"months-standAlone-wide": [
		"1æœˆ",
		"2æœˆ",
		"3æœˆ",
		"4æœˆ",
		"5æœˆ",
		"6æœˆ",
		"7æœˆ",
		"8æœˆ",
		"9æœˆ",
		"10æœˆ",
		"11æœˆ",
		"12æœˆ"
	],
	"timeFormat-short": "H:mm",
	"quarters-format-wide": [
		"ç¬¬1å››å?ŠæœŸ",
		"ç¬¬2å››å?ŠæœŸ",
		"ç¬¬3å››å?ŠæœŸ",
		"ç¬¬4å››å?ŠæœŸ"
	],
	"timeFormat-long": "H:mm:ss z",
	"field-year": "å¹´",
	"dateFormatItem-yMMM": "yå¹´Mæœˆ",
	"dateFormatItem-yQ": "y/Q",
	"field-hour": "æ™‚",
	"dateFormatItem-MMdd": "MM/dd",
	"months-format-abbr": [
		"1æœˆ",
		"2æœˆ",
		"3æœˆ",
		"4æœˆ",
		"5æœˆ",
		"6æœˆ",
		"7æœˆ",
		"8æœˆ",
		"9æœˆ",
		"10æœˆ",
		"11æœˆ",
		"12æœˆ"
	],
	"dateFormatItem-yyQ": "yy/Q",
	"timeFormat-full": "Hæ™‚mmåˆ†ssç§’ zzzz",
	"field-day-relative+0": "ä»Šæ—¥",
	"field-day-relative+1": "æ˜Žæ—¥",
	"field-day-relative+2": "æ˜Žå¾Œæ—¥",
	"dateFormatItem-H": "Hæ™‚",
	"field-day-relative+3": "3æ—¥å¾Œ",
	"months-standAlone-abbr": [
		"1æœˆ",
		"2æœˆ",
		"3æœˆ",
		"4æœˆ",
		"5æœˆ",
		"6æœˆ",
		"7æœˆ",
		"8æœˆ",
		"9æœˆ",
		"10æœˆ",
		"11æœˆ",
		"12æœˆ"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-wide": [
		"ç¬¬1å››å?ŠæœŸ",
		"ç¬¬2å››å?ŠæœŸ",
		"ç¬¬3å››å?ŠæœŸ",
		"ç¬¬4å››å?ŠæœŸ"
	],
	"dateFormatItem-M": "Mæœˆ",
	"days-standAlone-wide": [
		"æ—¥æ›œæ—¥",
		"æœˆæ›œæ—¥",
		"ç?«æ›œæ—¥",
		"æ°´æ›œæ—¥",
		"æœ¨æ›œæ—¥",
		"é‡‘æ›œæ—¥",
		"åœŸæ›œæ—¥"
	],
	"dateFormatItem-yyMMM": "yå¹´Mæœˆ",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"eraAbbr": [
		"BC",
		"AD"
	],
	"field-minute": "åˆ†",
	"field-dayperiod": "å?ˆå‰?/å?ˆå¾Œ",
	"days-standAlone-abbr": [
		"æ—¥",
		"æœˆ",
		"ç?«",
		"æ°´",
		"æœ¨",
		"é‡‘",
		"åœŸ"
	],
	"dateFormatItem-d": "dæ—¥",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "æ˜¨æ—¥",
	"dateFormatItem-h": "ahæ™‚",
	"dateTimeFormat-long": "{1}{0}",
	"field-day-relative+-2": "ä¸€æ˜¨æ—¥",
	"field-day-relative+-3": "3æ—¥å‰?",
	"dateFormatItem-MMMd": "Mæœˆdæ—¥",
	"dateFormatItem-MEd": "M/d(E)",
	"dateTimeFormat-full": "{1}{0}",
	"field-day": "æ—¥",
	"days-format-wide": [
		"æ—¥æ›œæ—¥",
		"æœˆæ›œæ—¥",
		"ç?«æ›œæ—¥",
		"æ°´æ›œæ—¥",
		"æœ¨æ›œæ—¥",
		"é‡‘æ›œæ—¥",
		"åœŸæ›œæ—¥"
	],
	"field-zone": "ã‚¿ã‚¤ãƒ ã‚¾ãƒ¼ãƒ³",
	"dateFormatItem-yyyyMM": "yyyy/MM",
	"dateFormatItem-y": "yå¹´",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateFormatItem-hm": "ah:mm",
	"dateFormatItem-GGGGyMd": "GGGGyå¹´Mæœˆdæ—¥",
	"days-format-abbr": [
		"æ—¥",
		"æœˆ",
		"ç?«",
		"æ°´",
		"æœ¨",
		"é‡‘",
		"åœŸ"
	],
	"dateFormatItem-yMMMd": "yå¹´Mæœˆdæ—¥",
	"eraNames": [
		"ç´€å…ƒå‰?",
		"è¥¿æš¦"
	],
	"days-format-narrow": [
		"æ—¥",
		"æœˆ",
		"ç?«",
		"æ°´",
		"æœ¨",
		"é‡‘",
		"åœŸ"
	],
	"field-month": "æœˆ",
	"days-standAlone-narrow": [
		"æ—¥",
		"æœˆ",
		"ç?«",
		"æ°´",
		"æœ¨",
		"é‡‘",
		"åœŸ"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "å?ˆå‰?",
	"dateFormat-short": "yy/MM/dd",
	"field-second": "ç§’",
	"dateFormatItem-yMMMEd": "yå¹´Mæœˆdæ—¥(EEE)",
	"dateFormatItem-Ed": "dæ—¥(EEE)",
	"field-week": "é€±",
	"dateFormat-medium": "yyyy/MM/dd",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hms": "ah:mm:ss",
	"dateFormatItem-yyyy": "yå¹´"
}
//end v1.x content
);