/*******************************************************************************
 * Copyright © 2011, 2012 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * IBM Corporation - initial API and implementation
 *
 *******************************************************************************/
package org.eclipse.edt.compiler.core.dev.tools;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Date;
import java.util.Iterator;
import java.util.TreeSet;

/**
 * @author jshavor
 *
 * output to the console IEGLConstants declarations for the EGL keywords
 * copy and paste the results to IEGLConstants
 */
public class EGLFlex2EGLKeywordTool {
	//This tool could use some work!!!
	//Currently you have to export error.flex to D:\error.flex.  (should find it in place)
	//You also have to edit the file to only show the keyword lines (note: there are currently 4 groups of these)
	//	(should be smart enough to find the right lines in the current file???)
	//Then run this tool and copy the results to EGLKeywordHandler.keywordNames
	//There is another problem that needs to be addressed.  The keywords in error.flex are all lowercase.
	//	The keywords in keywordNames need to be mixed case.  For now, you need to compare the differences
	//	to make the changes manually (can we make the keywords in error.flex be mixed case?)

	public static void main(String[] args) {
		StringBuffer stringBuffer = new StringBuffer();
		System.out.println();
		System.out.println("			//EGL keywords"); //$NON-NLS-1$
		System.out.print("			//Generated :  "); //$NON-NLS-1$
		System.out.println(new Date().toString());
		System.out.println("			//These keywords should be generated by org.eclipse.edt.compiler.internal.dev.tools.EGLFlex2EGLKeywordTool"); //$NON-NLS-1$
		
		TreeSet keywords = getKeywords();
		for (Iterator iter = keywords.iterator(); iter.hasNext();) {
			String keyword = (String) iter.next();
			stringBuffer.setLength(0);
			stringBuffer.append("			\""); //$NON-NLS-1$
			stringBuffer.append(keyword);
			stringBuffer.append("\", //$NON-NLS-1$"); //$NON-NLS-1$
			System.out.println(stringBuffer);
		}
	}

	public static TreeSet getKeywords() {
		TreeSet keywords = new TreeSet();
		try {
			String line = "";
			String keyword;
			File flexFile = new File("d:\\error.flex");
			BufferedReader flexStream = new BufferedReader(new InputStreamReader(new FileInputStream(flexFile)));
			while (line != null) {
				line = flexStream.readLine();
				if (line != null) {
					int begin = line.indexOf('"');
					keyword = line.substring(begin+1, line.length());
					int end = keyword.indexOf('"');
					keyword = keyword.substring(0, end);
					keywords.add(keyword);
				}
			}
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return keywords;
	}
}
