define(
//begin v1.x content
{
	"months-format-narrow": [
		"O",
		"Åž",
		"M",
		"N",
		"M",
		"H",
		"T",
		"A",
		"E",
		"E",
		"K",
		"A"
	],
	"field-weekday": "HaftanÄ±n GÃ¼nÃ¼",
	"dateFormatItem-yyQQQQ": "QQQQ yy",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "dd.MM.yyyy EEE",
	"dateFormatItem-MMMEd": "dd MMM E",
	"eraNarrow": [
		"MÃ–",
		"MS"
	],
	"dateFormat-long": "dd MMMM y",
	"months-format-wide": [
		"Ocak",
		"Åžubat",
		"Mart",
		"Nisan",
		"MayÄ±s",
		"Haziran",
		"Temmuz",
		"AÄŸustos",
		"EylÃ¼l",
		"Ekim",
		"KasÄ±m",
		"AralÄ±k"
	],
	"dateFormatItem-EEEd": "d EEE",
	"dayPeriods-format-wide-pm": "PM",
	"dateFormat-full": "dd MMMM y EEEE",
	"dateFormatItem-Md": "dd/MM",
	"field-era": "Miladi DÃ¶nem",
	"dateFormatItem-yM": "M/yyyy",
	"months-standAlone-wide": [
		"Ocak",
		"Åžubat",
		"Mart",
		"Nisan",
		"MayÄ±s",
		"Haziran",
		"Temmuz",
		"AÄŸustos",
		"EylÃ¼l",
		"Ekim",
		"KasÄ±m",
		"AralÄ±k"
	],
	"timeFormat-short": "HH:mm",
	"quarters-format-wide": [
		"1. Ã§eyrek",
		"2. Ã§eyrek",
		"3. Ã§eyrek",
		"4. Ã§eyrek"
	],
	"timeFormat-long": "HH:mm:ss z",
	"field-year": "YÄ±l",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yQ": "Q yyyy",
	"field-hour": "Saat",
	"months-format-abbr": [
		"Oca",
		"Åžub",
		"Mar",
		"Nis",
		"May",
		"Haz",
		"Tem",
		"AÄŸu",
		"Eyl",
		"Eki",
		"Kas",
		"Ara"
	],
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-full": "HH:mm:ss zzzz",
	"field-day-relative+0": "BugÃ¼n",
	"field-day-relative+1": "YarÄ±n",
	"field-day-relative+2": "YarÄ±ndan sonraki gÃ¼n",
	"dateFormatItem-H": "HH",
	"field-day-relative+3": "ÃœÃ§ gÃ¼n sonra",
	"months-standAlone-abbr": [
		"Oca",
		"Åžub",
		"Mar",
		"Nis",
		"May",
		"Haz",
		"Tem",
		"AÄŸu",
		"Eyl",
		"Eki",
		"Kas",
		"Ara"
	],
	"quarters-format-abbr": [
		"Ã‡1",
		"Ã‡2",
		"Ã‡3",
		"Ã‡4"
	],
	"quarters-standAlone-wide": [
		"1. Ã§eyrek",
		"2. Ã§eyrek",
		"3. Ã§eyrek",
		"4. Ã§eyrek"
	],
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"Pazar",
		"Pazartesi",
		"SalÄ±",
		"Ã‡arÅŸamba",
		"PerÅŸembe",
		"Cuma",
		"Cumartesi"
	],
	"dateFormatItem-MMMMd": "dd MMMM",
	"dateFormatItem-yyMMM": "MMM yy",
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-Hm": "HH:mm",
	"quarters-standAlone-abbr": [
		"Ã‡1",
		"Ã‡2",
		"Ã‡3",
		"Ã‡4"
	],
	"eraAbbr": [
		"MÃ–",
		"MS"
	],
	"field-minute": "Dakika",
	"field-dayperiod": "AM/PM",
	"days-standAlone-abbr": [
		"Paz",
		"Pzt",
		"Sal",
		"Ã‡ar",
		"Per",
		"Cum",
		"Cmt"
	],
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "DÃ¼n",
	"field-day-relative+-2": "Evvelsi gÃ¼n",
	"field-day-relative+-3": "ÃœÃ§ gÃ¼n Ã¶nce",
	"dateFormatItem-MMMd": "dd MMM",
	"dateFormatItem-MEd": "dd/MM E",
	"dateFormatItem-yMMMM": "MMMM y",
	"field-day": "GÃ¼n",
	"days-format-wide": [
		"Pazar",
		"Pazartesi",
		"SalÄ±",
		"Ã‡arÅŸamba",
		"PerÅŸembe",
		"Cuma",
		"Cumartesi"
	],
	"field-zone": "Saat Dilimi",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"O",
		"Åž",
		"M",
		"N",
		"M",
		"H",
		"T",
		"A",
		"E",
		"E",
		"K",
		"A"
	],
	"dateFormatItem-yyMM": "MM/yy",
	"dateFormatItem-hm": "h:mm a",
	"days-format-abbr": [
		"Paz",
		"Pzt",
		"Sal",
		"Ã‡ar",
		"Per",
		"Cum",
		"Cmt"
	],
	"eraNames": [
		"Milattan Ã–nce",
		"Milattan Sonra"
	],
	"days-format-narrow": [
		"P",
		"P",
		"S",
		"Ã‡",
		"P",
		"C",
		"C"
	],
	"field-month": "Ay",
	"days-standAlone-narrow": [
		"P",
		"P",
		"S",
		"Ã‡",
		"P",
		"C",
		"C"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "AM",
	"dateFormatItem-MMMMEd": "dd MMMM E",
	"dateFormat-short": "dd.MM.yyyy",
	"field-second": "Saniye",
	"dateFormatItem-yMMMEd": "dd MMM y EEE",
	"dateFormatItem-Ed": "d E",
	"field-week": "Hafta",
	"dateFormat-medium": "dd MMM y",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yyyy": "y"
}
//end v1.x content
);