package eglx.ui.rui;
public enum MappingKind {
	TYPE_PRIMITIVE_ALL(100),
	TYPE_PRIMITIVE_STRING(101),
	TYPE_PRIMITIVE_DATE(102),
	TYPE_PRIMITIVE_TIME(103),
	TYPE_PRIMITIVE_TIMESTAMP(104),
	TYPE_PRIMITIVE_BIGINT(105),
	TYPE_PRIMITIVE_BIN(106),
	TYPE_PRIMITIVE_DECIMAL(107),
	TYPE_PRIMITIVE_FLOAT(108),
	TYPE_PRIMITIVE_INT(109),
	TYPE_PRIMITIVE_NUM(110),
	TYPE_PRIMITIVE_MONEY(111),
	TYPE_PRIMITIVE_BOOLEAN(112),
	TYPE_PRIMITIVE_SMALLFLOAT(113),
	TYPE_PRIMITIVE_SMALLINT(114),
	TYPE_RECORD_ALL(200),
	TYPE_RECORD_SIMPLE(201),
	TYPE_RECORD_EMBED_RECORD(202),
	TYPE_RECORD_WITH_PRIMITIVE_ARRAY(203),
	TYPE_RECORD_WITH_RECORD_ARRAY(204);
	private final int value;
	MappingKind(int value) {
		this.value = value;
	}
	public int getValue() {
		return value;
	}
}
