define(
//begin v1.x content
{
	"field-dayperiod": "ÄŒasÅ¥ dÅˆa",
	"dateFormatItem-yQ": "Q yyyy",
	"dayPeriods-format-wide-pm": "popoludnÃ­",
	"field-minute": "MinÃºta",
	"eraNames": [
		"pred n.l.",
		"n.l."
	],
	"dateFormatItem-MMMEd": "E, d. MMM",
	"field-day-relative+-1": "VÄ?era",
	"field-weekday": "DeÅˆ v tÃ½Å¾dni",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "PredvÄ?erom",
	"field-day-relative+-3": "Pred tromi dÅˆami",
	"days-standAlone-wide": [
		"nedeÄ¾a",
		"pondelok",
		"utorok",
		"streda",
		"Å¡tvrtok",
		"piatok",
		"sobota"
	],
	"months-standAlone-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"field-era": "Ã‰ra",
	"field-hour": "Hodina",
	"dayPeriods-format-wide-am": "dopoludnia",
	"timeFormat-full": "H:mm:ss zzzz",
	"months-standAlone-abbr": [
		"jan",
		"feb",
		"mar",
		"apr",
		"mÃ¡j",
		"jÃºn",
		"jÃºl",
		"aug",
		"sep",
		"okt",
		"nov",
		"dec"
	],
	"dateFormatItem-yMMM": "LLL y",
	"field-day-relative+0": "Dnes",
	"field-day-relative+1": "Zajtra",
	"days-standAlone-narrow": [
		"N",
		"P",
		"U",
		"S",
		"Å ",
		"P",
		"S"
	],
	"eraAbbr": [
		"pred n.l.",
		"n.l."
	],
	"field-day-relative+2": "Pozajtra",
	"field-day-relative+3": "O tri dni",
	"dateFormatItem-yyyyMMMM": "LLLL y",
	"dateFormat-long": "d. MMMM y",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-EEEd": "EEE, d.",
	"field-zone": "PÃ¡smo",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "d.M.yyyy",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yyQQQQ": "QQQQ yy",
	"quarters-standAlone-wide": [
		"1. Å¡tvrÅ¥rok",
		"2. Å¡tvrÅ¥rok",
		"3. Å¡tvrÅ¥rok",
		"4. Å¡tvrÅ¥rok"
	],
	"dateFormatItem-yMMMM": "LLLL y",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "Rok",
	"months-standAlone-wide": [
		"januÃ¡r",
		"februÃ¡r",
		"marec",
		"aprÃ­l",
		"mÃ¡j",
		"jÃºn",
		"jÃºl",
		"august",
		"september",
		"oktÃ³ber",
		"november",
		"december"
	],
	"field-week": "TÃ½Å¾deÅˆ",
	"dateFormatItem-MMMMEd": "E, d. MMMM",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-long": "H:mm:ss z",
	"months-format-abbr": [
		"jan",
		"feb",
		"mar",
		"apr",
		"mÃ¡j",
		"jÃºn",
		"jÃºl",
		"aug",
		"sep",
		"okt",
		"nov",
		"dec"
	],
	"timeFormat-short": "H:mm",
	"dateFormatItem-H": "H",
	"field-month": "Mesiac",
	"dateFormatItem-MMMMd": "d. MMMM",
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"days-format-abbr": [
		"ne",
		"po",
		"ut",
		"st",
		"Å¡t",
		"pi",
		"so"
	],
	"dateFormatItem-mmss": "mm:ss",
	"days-format-narrow": [
		"N",
		"P",
		"U",
		"S",
		"Å ",
		"P",
		"S"
	],
	"field-second": "Sekunda",
	"field-day": "DeÅˆ",
	"dateFormatItem-MEd": "E, d.M.",
	"months-format-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"days-standAlone-abbr": [
		"ne",
		"po",
		"ut",
		"st",
		"Å¡t",
		"pi",
		"so"
	],
	"dateFormat-short": "d.M.yyyy",
	"dateFormatItem-yyyyM": "M.yyyy",
	"dateFormatItem-yMMMEd": "EEE, d. MMM y",
	"dateFormat-full": "EEEE, d. MMMM y",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yMEd": "EEE, d.M.yyyy",
	"months-format-wide": [
		"januÃ¡ra",
		"februÃ¡ra",
		"marca",
		"aprÃ­la",
		"mÃ¡ja",
		"jÃºna",
		"jÃºla",
		"augusta",
		"septembra",
		"oktÃ³bra",
		"novembra",
		"decembra"
	],
	"dateFormatItem-d": "d.",
	"quarters-format-wide": [
		"1. Å¡tvrÅ¥rok",
		"2. Å¡tvrÅ¥rok",
		"3. Å¡tvrÅ¥rok",
		"4. Å¡tvrÅ¥rok"
	],
	"days-format-wide": [
		"nedeÄ¾a",
		"pondelok",
		"utorok",
		"streda",
		"Å¡tvrtok",
		"piatok",
		"sobota"
	],
	"eraNarrow": [
		"pred n.l.",
		"n.l."
	]
}
//end v1.x content
);