/*******************************************************************************
 * Copyright © 2011, 2013 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * IBM Corporation - initial API and implementation
 *
 *******************************************************************************/
package org.eclipse.edt.compiler.dev.tools;

import java.util.Date;

import org.eclipse.edt.compiler.internal.EGLMnemonicHandler;


/**
 * @author dollar
 *
 * output to the console IEGLConstants declarations for the EGL keywords
 * copy and paste the results to IEGLConstants 
 */
public class EGLMnemonicTool {

	public static void main(String[] args) {
		StringBuffer stringBuffer = new StringBuffer();
		System.out.println();
		System.out.println("	//EGL mnemonics"); //$NON-NLS-1$
		System.out.print("	//Generated :  "); //$NON-NLS-1$
		System.out.println(new Date().toString());
		System.out.println("	//These mnemonics should be generated by org.eclipse.edt.compiler.internal.dev.tools.EGLMnemonicTool"); //$NON-NLS-1$
		String mnemonics[] = EGLMnemonicHandler.getMnemonicNames();
		for (int i = 0; i < mnemonics.length; i++) {
			String mnemonic = mnemonics[i];
			stringBuffer.setLength(0);
			stringBuffer.append("	public static final String "); //$NON-NLS-1$
			stringBuffer.append("MNEMONIC_"); //$NON-NLS-1$
			stringBuffer.append(mnemonic.toUpperCase());
			stringBuffer.append(" = \""); //$NON-NLS-1$
			stringBuffer.append(mnemonic);
			stringBuffer.append("\";  //$NON-NLS-1$"); //$NON-NLS-1$
			System.out.println(stringBuffer);
		}
	}
}
