/*******************************************************************************
 * Copyright © 2011, 2012 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * IBM Corporation - initial API and implementation
 *
 *******************************************************************************/
package org.eclipse.edt.compiler.dev.tools; 
 
import java.util.Date;

import org.eclipse.edt.compiler.internal.EGLPropertiesHandler;

/**
 * @author dollar
 *
 * output to the console IEGLConstants declarations for the EGL properties
 * copy and paste the results to IEGLConstants
 */
public class EGLPropertiesTool {

	public static void main(String[] args) {
		StringBuffer stringBuffer = new StringBuffer();
		System.out.println();
		System.out.println("	//EGL properties"); //$NON-NLS-1$
		System.out.print("	//Generated :  "); //$NON-NLS-1$
		System.out.println(new Date().toString());
		System.out.println("	//These properties should be generated by org.eclipse.edt.compiler.internal.dev.tools.EGLPropertiesTool"); //$NON-NLS-1$
		String properties[] = EGLPropertiesHandler.getAllPropertyNames();
		for (int i = 0; i < properties.length; i++) {
			String keyword = properties[i];
			stringBuffer.setLength(0);
			stringBuffer.append("	public static final String "); //$NON-NLS-1$
			stringBuffer.append("PROPERTY_"); //$NON-NLS-1$
			stringBuffer.append(keyword.toUpperCase());
			stringBuffer.append(" = \""); //$NON-NLS-1$
			stringBuffer.append(keyword);
			stringBuffer.append("\";  //$NON-NLS-1$"); //$NON-NLS-1$
			System.out.println(stringBuffer);
		}	
	}
}
