define(
//begin v1.x content
{
	"months-format-narrow": [
		"Î™",
		"Î¦",
		"Îœ",
		"Î‘",
		"Îœ",
		"Î™",
		"Î™",
		"Î‘",
		"Î£",
		"ÎŸ",
		"Î?",
		"Î”"
	],
	"field-weekday": "Î—Î¼Î­Ï?Î± ÎµÎ²Î´Î¿Î¼Î¬Î´Î±Ï‚",
	"dateFormatItem-yyQQQQ": "QQQQ yy",
	"dateFormatItem-yQQQ": "y QQQ",
	"dateFormatItem-yMEd": "EEE, d/M/yyyy",
	"dateFormatItem-MMMEd": "E, d MMM",
	"eraNarrow": [
		"Ï€.Î§.",
		"Î¼.Î§."
	],
	"dateFormat-long": "d MMMM y",
	"months-format-wide": [
		"Î™Î±Î½Î¿Ï…Î±Ï?Î¯Î¿Ï…",
		"Î¦ÎµÎ²Ï?Î¿Ï…Î±Ï?Î¯Î¿Ï…",
		"ÎœÎ±Ï?Ï„Î¯Î¿Ï…",
		"Î‘Ï€Ï?Î¹Î»Î¯Î¿Ï…",
		"ÎœÎ±Î?Î¿Ï…",
		"Î™Î¿Ï…Î½Î¯Î¿Ï…",
		"Î™Î¿Ï…Î»Î¯Î¿Ï…",
		"Î‘Ï…Î³Î¿Ï?ÏƒÏ„Î¿Ï…",
		"Î£ÎµÏ€Ï„ÎµÎ¼Î²Ï?Î¯Î¿Ï…",
		"ÎŸÎºÏ„Ï‰Î²Ï?Î¯Î¿Ï…",
		"Î?Î¿ÎµÎ¼Î²Ï?Î¯Î¿Ï…",
		"Î”ÎµÎºÎµÎ¼Î²Ï?Î¯Î¿Ï…"
	],
	"dateFormatItem-EEEd": "EEE d",
	"dayPeriods-format-wide-pm": "Î¼.Î¼.",
	"dateFormat-full": "EEEE, d MMMM y",
	"dateFormatItem-Md": "d/M",
	"field-era": "Î ÎµÏ?Î¯Î¿Î´Î¿Ï‚",
	"dateFormatItem-yM": "M/yyyy",
	"months-standAlone-wide": [
		"Î™Î±Î½Î¿Ï…Î¬Ï?Î¹Î¿Ï‚",
		"Î¦ÎµÎ²Ï?Î¿Ï…Î¬Ï?Î¹Î¿Ï‚",
		"ÎœÎ¬Ï?Ï„Î¹Î¿Ï‚",
		"Î‘Ï€Ï?Î¯Î»Î¹Î¿Ï‚",
		"ÎœÎ¬Î¹Î¿Ï‚",
		"Î™Î¿Ï?Î½Î¹Î¿Ï‚",
		"Î™Î¿Ï?Î»Î¹Î¿Ï‚",
		"Î‘Ï?Î³Î¿Ï…ÏƒÏ„Î¿Ï‚",
		"Î£ÎµÏ€Ï„Î­Î¼Î²Ï?Î¹Î¿Ï‚",
		"ÎŸÎºÏ„ÏŽÎ²Ï?Î¹Î¿Ï‚",
		"Î?Î¿Î­Î¼Î²Ï?Î¹Î¿Ï‚",
		"Î”ÎµÎºÎ­Î¼Î²Ï?Î¹Î¿Ï‚"
	],
	"timeFormat-short": "h:mm a",
	"quarters-format-wide": [
		"1Î¿ Ï„Ï?Î¯Î¼Î·Î½Î¿",
		"2Î¿ Ï„Ï?Î¯Î¼Î·Î½Î¿",
		"3Î¿ Ï„Ï?Î¯Î¼Î·Î½Î¿",
		"4Î¿ Ï„Ï?Î¯Î¼Î·Î½Î¿"
	],
	"timeFormat-long": "h:mm:ss a z",
	"field-year": "ÎˆÏ„Î¿Ï‚",
	"dateFormatItem-yMMM": "LLL y",
	"dateFormatItem-yQ": "y Q",
	"dateFormatItem-yyyyMMMM": "LLLL y",
	"field-hour": "Î?Ï?Î±",
	"dateFormatItem-MMdd": "dd/MM",
	"months-format-abbr": [
		"Î™Î±Î½",
		"Î¦ÎµÎ²",
		"ÎœÎ±Ï?",
		"Î‘Ï€Ï?",
		"ÎœÎ±ÏŠ",
		"Î™Î¿Ï…Î½",
		"Î™Î¿Ï…Î»",
		"Î‘Ï…Î³",
		"Î£ÎµÏ€",
		"ÎŸÎºÏ„",
		"Î?Î¿Îµ",
		"Î”ÎµÎº"
	],
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-full": "h:mm:ss a zzzz",
	"field-day-relative+0": "Î£Î®Î¼ÎµÏ?Î±",
	"field-day-relative+1": "Î‘Ï?Ï?Î¹Î¿",
	"field-day-relative+2": "ÎœÎµÎ¸Î±Ï?Ï?Î¹Î¿",
	"dateFormatItem-H": "HH",
	"field-day-relative+3": "Î£Îµ Ï„Ï?ÎµÎ¹Ï‚ Î·Î¼Î­Ï?ÎµÏ‚ Î±Ï€ÏŒ Ï„ÏŽÏ?Î±",
	"months-standAlone-abbr": [
		"Î™Î±Î½",
		"Î¦ÎµÎ²",
		"ÎœÎ±Ï?",
		"Î‘Ï€Ï?",
		"ÎœÎ±ÏŠ",
		"Î™Î¿Ï…Î½",
		"Î™Î¿Ï…Î»",
		"Î‘Ï…Î³",
		"Î£ÎµÏ€",
		"ÎŸÎºÏ„",
		"Î?Î¿Îµ",
		"Î”ÎµÎº"
	],
	"quarters-format-abbr": [
		"Î¤1",
		"Î¤2",
		"Î¤3",
		"Î¤4"
	],
	"quarters-standAlone-wide": [
		"1Î¿ Ï„Ï?Î¯Î¼Î·Î½Î¿",
		"2Î¿ Ï„Ï?Î¯Î¼Î·Î½Î¿",
		"3Î¿ Ï„Ï?Î¯Î¼Î·Î½Î¿",
		"4Î¿ Ï„Ï?Î¯Î¼Î·Î½Î¿"
	],
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"ÎšÏ…Ï?Î¹Î±ÎºÎ®",
		"Î”ÎµÏ…Ï„Î­Ï?Î±",
		"Î¤Ï?Î¯Ï„Î·",
		"Î¤ÎµÏ„Î¬Ï?Ï„Î·",
		"Î Î­Î¼Ï€Ï„Î·",
		"Î Î±Ï?Î±ÏƒÎºÎµÏ…Î®",
		"Î£Î¬Î²Î²Î±Ï„Î¿"
	],
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-yyMMM": "LLL yy",
	"timeFormat-medium": "h:mm:ss a",
	"dateFormatItem-Hm": "HH:mm",
	"quarters-standAlone-abbr": [
		"Î¤1",
		"Î¤2",
		"Î¤3",
		"Î¤4"
	],
	"eraAbbr": [
		"Ï€.Î§.",
		"Î¼.Î§."
	],
	"field-minute": "Î›ÎµÏ€Ï„ÏŒ",
	"field-dayperiod": "Ï€.Î¼./Î¼.Î¼.",
	"days-standAlone-abbr": [
		"ÎšÏ…Ï?",
		"Î”ÎµÏ…",
		"Î¤Ï?Î¹",
		"Î¤ÎµÏ„",
		"Î ÎµÎ¼",
		"Î Î±Ï?",
		"Î£Î±Î²"
	],
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "Î§Î¸ÎµÏ‚",
	"field-day-relative+-2": "Î Ï?Î¿Ï‡Î¸Î­Ï‚",
	"field-day-relative+-3": "Î Ï?Î¹Î½ Î±Ï€ÏŒ Ï„Ï?ÎµÎ¹Ï‚ Î·Î¼Î­Ï?ÎµÏ‚",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E, d/M",
	"field-day": "Î—Î¼Î­Ï?Î±",
	"days-format-wide": [
		"ÎšÏ…Ï?Î¹Î±ÎºÎ®",
		"Î”ÎµÏ…Ï„Î­Ï?Î±",
		"Î¤Ï?Î¯Ï„Î·",
		"Î¤ÎµÏ„Î¬Ï?Ï„Î·",
		"Î Î­Î¼Ï€Ï„Î·",
		"Î Î±Ï?Î±ÏƒÎºÎµÏ…Î®",
		"Î£Î¬Î²Î²Î±Ï„Î¿"
	],
	"field-zone": "Î–ÏŽÎ½Î·",
	"dateFormatItem-yyyyMM": "MM/yyyy",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"Î™",
		"Î¦",
		"Îœ",
		"Î‘",
		"Îœ",
		"Î™",
		"Î™",
		"Î‘",
		"Î£",
		"ÎŸ",
		"Î?",
		"Î”"
	],
	"dateFormatItem-yyMM": "MM/yy",
	"days-format-abbr": [
		"ÎšÏ…Ï?",
		"Î”ÎµÏ…",
		"Î¤Ï?Î¹",
		"Î¤ÎµÏ„",
		"Î ÎµÎ¼",
		"Î Î±Ï?",
		"Î£Î±Î²"
	],
	"eraNames": [
		"Ï€.Î§.",
		"Î¼.Î§."
	],
	"days-format-narrow": [
		"Îš",
		"Î”",
		"Î¤",
		"Î¤",
		"Î ",
		"Î ",
		"Î£"
	],
	"field-month": "ÎœÎ®Î½Î±Ï‚",
	"days-standAlone-narrow": [
		"Îš",
		"Î”",
		"Î¤",
		"Î¤",
		"Î ",
		"Î ",
		"Î£"
	],
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-HHmm": "HH:mm",
	"dayPeriods-format-wide-am": "Ï€.Î¼.",
	"dateFormatItem-MMMMEd": "E, d MMMM",
	"dateFormatItem-MMMMdd": "dd MMMM",
	"dateFormat-short": "d/M/yy",
	"field-second": "Î”ÎµÏ…Ï„ÎµÏ?ÏŒÎ»ÎµÏ€Ï„Î¿",
	"dateFormatItem-yMMMEd": "EEE, d MMM y",
	"dateFormatItem-Ed": "E d",
	"field-week": "Î•Î²Î´Î¿Î¼Î¬Î´Î±",
	"dateFormat-medium": "d MMM y",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-yyyy": "y"
}
//end v1.x content
);